#cloud-config
output: { all: '| tee -a /var/log/cloud-init-output.log' }

package_update: true
# package_upgrade: true

packages:
  - build-essential
  - sudo

chef:
  install_type: packages
  server_url: "http://127.0.0.1:8889"
  validation_name: system
  exec: false

write_files:
  - path: /etc/cron.d/booted
    content: '@reboot ( touch /tmp/booted )'

runcmd:
  - set -x

  # Instsall Chef
  - wget "https://packages.chef.io/files/stable/chef-workstation/20.11.180/ubuntu/20.04/chef-workstation_20.11.180-1_amd64.deb" -O /tmp/chef.deb
  - sudo dpkg -i /tmp/chef.deb
  - chef -v

  # Download the cookbook
  - mkdir /opt/algo && cd /opt/algo
  - wget "${algo_release_url}" -O - -q | tar zxfv - -C /opt/algo/

  # Remove sshguards
  - sudo apt-get remove -y --purge sshguard || true

  # Reboot
  - '[ -f /var/run/reboot-required ] && shutdown -r now "Algo updates triggered" || touch /tmp/booted'

